### ISSUE TITLE
Volume drivers containing slash do not work

### ISSUE THREAD

**Issue by rodneygp** [swarmpit/installer#1]
Hi!
We are using rexray/rbd as a volume driver. When I enter it, there is an error message appearing during install and my volume is created with default local driver.

You can fix this issue with replacing slashes on line 138 as sed s's separators with something else, that will unlikely be used in plugin name (I use '#'):
sed -i 's#driver: local#'"driver: $VOLUME_DRIVER"'#' swarmpit/docker-compose.yml

Also, I would suggest to add
set -eo pipefail
At the beginning of the script to make sure your script "fails fast" and doesn't postpone the issue to the later stages. Read here more about it https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/

Regards,

Rodion

**Comment by nohaapav** [comment]
@rodneygp Thanks for reporting. You can even submit PR if u wish. Every contribution is more than welcome ;)
